version: '3.8'
services:
  dev-webfluxblog-notification-sender-service: # The name of the service
    container_name: dev-webfluxblog-notification-sender-service  # Setting the container name
    image: dev-webfluxblog-notification-sender-service-local-image
    restart: always # Always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8118:8118" # Map The current port
    networks:
      - dev-webfluxblog-network-overlay
    volumes:
      - dev-webfluxblog-notification-sender-service-local-volume:/uploads
      - /root/logs:/usr/app/logs
    environment:
      spring.profiles.active: dev


networks:
  dev-webfluxblog-network-overlay:
    external: true

volumes:
  dev-webfluxblog-notification-sender-service-local-volume:
    name: dev-webfluxblog-notification-sender-service-local-volume

# To build, docker-compose up --build -d or generally ./gradlew bootJar && docker-compose up --build -d