version: '3.8'
services:
  prod-webfluxblog-notification-sender-service: # The name of the service
    container_name: prod-webfluxblog-notification-sender-service  # Setting the container name
    image: prod-webfluxblog-notification-sender-service-local-image
    restart: always # Always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8116:8116" # Map The current port
    networks:
      - prod-webfluxblog-network-overlay
    volumes:
      - prod-webfluxblog-notification-sender-service-local-volume:/uploads
      - /root/logs:/usr/app/logs
    environment:
      spring.profiles.active: prod


networks:
  prod-webfluxblog-network-overlay:
    external: true

volumes:
  prod-webfluxblog-notification-sender-service-local-volume:
    name: prod-webfluxblog-notification-sender-service-local-volume

# To build, docker-compose up --build -d or generally ./gradlew bootJar && docker-compose up --build -d