debug: false
server:
  error:
    include-message: always
    include-exception: false
    include-binding-errors: always
    include-stacktrace: always
  port: 8116

logging:
  level:
    com.mathias8dev: TRACE
  file:
    name: ./logs/prod-${spring.application.name}.log




spring:
  application:
    name: notification-sender-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://prod-webfluxblog-authorization-server-service:8110/oauth2/jwks
          issuer-uri: http://prod-webfluxblog-authorization-server-service:8110

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: kalipemathias.pro@gmail.com
    password: dkab crmr gwqb sjcn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false




# Custom
webfluxblog:
  gateway:
    baseurl: http://prod-webfluxblog-gateway-service:8080
    api-url: http://prod-webfluxblog-gateway-service:8080/api


# Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://prod-webfluxblog-eureka-server-service:8083/eureka
  instance:
    hostname: prod-webfluxblog-eureka-server-service
    prefer-ip-address: true




# SMS
twilio:
  api:
    account-sid:
    auth-token:
    phone-number:
